#!/bin/sh

# See how we were called.
case "$1" in
    start)
        echo -n "Starting ifplugd: "
        /usr/sbin/ifplugd -r /etc/ifplugd.action
        echo
        ;;
    stop)
	echo -n "Shutting down ifplugd: "
	killall ifplugd
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
